version: '3.9'

services:
  db:
    container_name: db-task
    image: mysql
    ports:
      - 3307:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: nsdgvjklosngojwsn
      MYSQL_PASSWORD: vnladivajiovjwoej
      MYSQL_USER: user

  phpmyadmin:
    container_name: phpmyadmin-task
    image: phpmyadmin
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql-data:
    driver: local